# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gio/CLionProjects/untitled8

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gio/CLionProjects/untitled8

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gio/CLionProjects/untitled8/CMakeFiles /home/gio/CLionProjects/untitled8//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gio/CLionProjects/untitled8/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stream_analysis

# Build rule for target.
stream_analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stream_analysis
.PHONY : stream_analysis

# fast build rule for target.
stream_analysis/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/build
.PHONY : stream_analysis/fast

src/capture.o: src/capture.cpp.o
.PHONY : src/capture.o

# target to build an object file
src/capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/capture.cpp.o
.PHONY : src/capture.cpp.o

src/capture.i: src/capture.cpp.i
.PHONY : src/capture.i

# target to preprocess a source file
src/capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/capture.cpp.i
.PHONY : src/capture.cpp.i

src/capture.s: src/capture.cpp.s
.PHONY : src/capture.s

# target to generate assembly for a file
src/capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/capture.cpp.s
.PHONY : src/capture.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/ffmpeg_capture.o: src/ffmpeg_capture.cpp.o
.PHONY : src/ffmpeg_capture.o

# target to build an object file
src/ffmpeg_capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/ffmpeg_capture.cpp.o
.PHONY : src/ffmpeg_capture.cpp.o

src/ffmpeg_capture.i: src/ffmpeg_capture.cpp.i
.PHONY : src/ffmpeg_capture.i

# target to preprocess a source file
src/ffmpeg_capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/ffmpeg_capture.cpp.i
.PHONY : src/ffmpeg_capture.cpp.i

src/ffmpeg_capture.s: src/ffmpeg_capture.cpp.s
.PHONY : src/ffmpeg_capture.s

# target to generate assembly for a file
src/ffmpeg_capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/ffmpeg_capture.cpp.s
.PHONY : src/ffmpeg_capture.cpp.s

src/frame_analysis.o: src/frame_analysis.cpp.o
.PHONY : src/frame_analysis.o

# target to build an object file
src/frame_analysis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/frame_analysis.cpp.o
.PHONY : src/frame_analysis.cpp.o

src/frame_analysis.i: src/frame_analysis.cpp.i
.PHONY : src/frame_analysis.i

# target to preprocess a source file
src/frame_analysis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/frame_analysis.cpp.i
.PHONY : src/frame_analysis.cpp.i

src/frame_analysis.s: src/frame_analysis.cpp.s
.PHONY : src/frame_analysis.s

# target to generate assembly for a file
src/frame_analysis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/frame_analysis.cpp.s
.PHONY : src/frame_analysis.cpp.s

src/gstreamer_capture.o: src/gstreamer_capture.cpp.o
.PHONY : src/gstreamer_capture.o

# target to build an object file
src/gstreamer_capture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/gstreamer_capture.cpp.o
.PHONY : src/gstreamer_capture.cpp.o

src/gstreamer_capture.i: src/gstreamer_capture.cpp.i
.PHONY : src/gstreamer_capture.i

# target to preprocess a source file
src/gstreamer_capture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/gstreamer_capture.cpp.i
.PHONY : src/gstreamer_capture.cpp.i

src/gstreamer_capture.s: src/gstreamer_capture.cpp.s
.PHONY : src/gstreamer_capture.s

# target to generate assembly for a file
src/gstreamer_capture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/gstreamer_capture.cpp.s
.PHONY : src/gstreamer_capture.cpp.s

src/helpers.o: src/helpers.cpp.o
.PHONY : src/helpers.o

# target to build an object file
src/helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/helpers.cpp.o
.PHONY : src/helpers.cpp.o

src/helpers.i: src/helpers.cpp.i
.PHONY : src/helpers.i

# target to preprocess a source file
src/helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/helpers.cpp.i
.PHONY : src/helpers.cpp.i

src/helpers.s: src/helpers.cpp.s
.PHONY : src/helpers.s

# target to generate assembly for a file
src/helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/helpers.cpp.s
.PHONY : src/helpers.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/metrics.o: src/metrics.cpp.o
.PHONY : src/metrics.o

# target to build an object file
src/metrics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/metrics.cpp.o
.PHONY : src/metrics.cpp.o

src/metrics.i: src/metrics.cpp.i
.PHONY : src/metrics.i

# target to preprocess a source file
src/metrics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/metrics.cpp.i
.PHONY : src/metrics.cpp.i

src/metrics.s: src/metrics.cpp.s
.PHONY : src/metrics.s

# target to generate assembly for a file
src/metrics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/metrics.cpp.s
.PHONY : src/metrics.cpp.s

src/stream_analyzer.o: src/stream_analyzer.cpp.o
.PHONY : src/stream_analyzer.o

# target to build an object file
src/stream_analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/stream_analyzer.cpp.o
.PHONY : src/stream_analyzer.cpp.o

src/stream_analyzer.i: src/stream_analyzer.cpp.i
.PHONY : src/stream_analyzer.i

# target to preprocess a source file
src/stream_analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/stream_analyzer.cpp.i
.PHONY : src/stream_analyzer.cpp.i

src/stream_analyzer.s: src/stream_analyzer.cpp.s
.PHONY : src/stream_analyzer.s

# target to generate assembly for a file
src/stream_analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stream_analysis.dir/build.make CMakeFiles/stream_analysis.dir/src/stream_analyzer.cpp.s
.PHONY : src/stream_analyzer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stream_analysis"
	@echo "... src/capture.o"
	@echo "... src/capture.i"
	@echo "... src/capture.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/ffmpeg_capture.o"
	@echo "... src/ffmpeg_capture.i"
	@echo "... src/ffmpeg_capture.s"
	@echo "... src/frame_analysis.o"
	@echo "... src/frame_analysis.i"
	@echo "... src/frame_analysis.s"
	@echo "... src/gstreamer_capture.o"
	@echo "... src/gstreamer_capture.i"
	@echo "... src/gstreamer_capture.s"
	@echo "... src/helpers.o"
	@echo "... src/helpers.i"
	@echo "... src/helpers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/metrics.o"
	@echo "... src/metrics.i"
	@echo "... src/metrics.s"
	@echo "... src/stream_analyzer.o"
	@echo "... src/stream_analyzer.i"
	@echo "... src/stream_analyzer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

